name: Unit tests

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: flutter-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

